name = "TexturedPerovskiteSolarCells"
uuid = "25b13238-729e-4bd4-a261-8345ff999ea8"
authors = ["Dilara Abdel <dilara.abdel@wias-berlin.de>", "Patrick Jaap <patrick.jaap@wias-berlin.de>", "Jürgen Fuhrmann <juergen.fuhrmann@wias-berlin.de>", "Patricio Farrell <patricio.farrell@wias-berlin.de>"]
version = "1.0.0"

[deps]
ChargeTransport = "25c3eafe-d88c-11e9-3031-f396758f002a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
GridVisualize = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SimplexGridFactory = "57bfcd06-606e-45d6-baf4-4ba06da0efd5"
Triangulate = "f7e6ffb2-c36d-4f8f-a77e-16e897189344"
VoronoiFVM = "82b139dc-5afc-11e9-35da-9b9bdfd336f3"

[compat]
Aqua = "0.8.12"
ChargeTransport = "^0.4"
DelimitedFiles = "1.9.1"
ExtendableGrids = "1.13.1"
GridVisualize = "1.12.0"
Interpolations = "0.15.1"
LinearAlgebra = "^1.10"
LinearSolve = "3.14.0"
NPZ = "0.4.3"
PyCall = "1.96.4"
PyPlot = "2.11.6"
Roots = "2.2.7"
SimplexGridFactory = "2.4.0"
Test = "1.10.0"
Triangulate = "2.4.0"
VoronoiFVM = "2.10.1"
julia = "^1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
